# Generated by Django 5.1.4 on 2025-05-15 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
